config/routes.rb
Rails.application.routes.draw do
  get 'subscribers/index'

  get 'subscribers/create'

  get 'general/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'general#index'

  get 'general/video/:id' => 'general#index', as: :home
  resource :subscribers

end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/css_class.rb
# == Schema Information
#
# Table name: css_classes
#
#  id         :integer          not null, primary key
#  name       :string
#  type_of    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CssClass < ActiveRecord::Base
  has_and_belongs_to_many :sections
end

app/models/header.rb
# == Schema Information
#
# Table name: headers
#
#  id             :integer          not null, primary key
#  url            :string
#  css_identifier :string
#  css_class      :string
#  title          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Header < ActiveRecord::Base
end

app/models/section.rb
# == Schema Information
#
# Table name: sections
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Section < ActiveRecord::Base
  has_and_belongs_to_many :css_classes


end

app/models/subscriber.rb
# == Schema Information
#
# Table name: subscribers
#
#  id         :integer          not null, primary key
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subscriber < ActiveRecord::Base
end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id                         :integer          not null, primary key
#  url                        :string
#  title                      :string
#  description                :text
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  image_preview_file_name    :string
#  image_preview_content_type :string
#  image_preview_file_size    :integer
#  image_preview_updated_at   :datetime
#

class Video < ActiveRecord::Base
  has_attached_file :image_preview, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image_preview, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  before_action :get_menu

  def get_menu
    @headers = Header.all
  end

  def index
    @videos = Video.all
    @sections = Section.order :position
    if params[:id]
      @current_video = Video.find params[:id]
    else
      @current_video = Video.first
    end

  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def index
  end

  def create

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/general/index.html.haml
%nav.navbar.navbar-default.navbar-fixed-top.navbar-init
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header.page-scroll
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a{:href => "#page-top"} #{image_tag 'logo_index', class: 'logo-index'}
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li.hidden.active
          %a{:href => "#page-top"}
        - @headers.each do |header|
          %li.page-scroll.menu-header
            %a{:href => "#", class:'menu menu-header-init'} #{header.title}
  / /.navbar-collapse
  / /.container-fluid
.container-fluid.container-relative
  .row
    .banner
      .grid-texture
      .button{class: 'btn btn-banner btn-watch'}
        Watch this AD
      .button{class: 'btn btn-banner btn-facebook'}
        Share on facebook
      %a{href: @current_video.url}
        = image_tag @current_video.image_preview.url, class: 'video-background'
.container-fluid.preview-section
  .row
    .col-md-10.col-md-offset-1.container-video
      - @videos.each do |video|
        .col-md-4
          = link_to home_path video do
            = image_tag video.image_preview.url, class: 'video-preview'
.container-fluid.subscribe-section
  .row
    .col-md-6.col-md-offset-3
      = form_tag(subscribers_path, method: 'post') do
        = label_tag 'Give us your email to donate every week:'
        = text_field_tag 'email', nil, class: "form-control", placeholder: "Your email address"
        = submit_tag 'Subscribe', class:'btn btn-subscribe'
- @sections.each do |section|
  .container-fluid.dynamic-section
    .row
      .col-md-12
        %h1.text-center
          = section.title
        - if section.content
          %p
            = section.content

app/views/general/subscribe.html.haml
Subscrito!

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WadchingRails
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = google_webfonts_init(google: ['Roboto', 'Comfortaa:300', 'Monda'])
    = csrf_meta_tags
  %body

    - if notice || alert
      %p.notice= notice
      %p.alert= alert
    = yield

app/views/subscribers/create.html.erb
<h1>Subscribers#create</h1>
<p>Find me in app/views/subscribers/create.html.erb</p>

app/views/subscribers/index.html.erb
<h1>Subscribers#index</h1>
<p>Find me in app/views/subscribers/index.html.erb</p>